### ISSUE TITLE
Font @2x

### ISSUE THREAD

**Issue by baikepan** [PrimaryFeather/Sparrow-Framework#1005]
File: SPBitmapFont.m
Function: - (void)parser:(NSXMLParser_)parser didStartElement:(NSString_)elementName

@"info" and @"common" tokens need to divide mSize and mLineHeight (respectively) by mFontTexture.scale if mFontTexture != nil. Otherwise the conditional scaling in the @"page" token is skipped for atlas-based fonts.

**Comment by PrimaryFeather** [comment]
More info on this can be found [here](http://forum.sparrow-framework.org/topic/font-scale-2x).
Thanks for creating the issue! Will be fixed asap, sorry for the delay.

**Comment by PrimaryFeather** [comment]
fixed wrong scale setting when loading bitmap font with custom texture (closed by 2b9da55b6e2e6af76d3e7f03c5b18ff324a60dcb)

**Comment by PrimaryFeather** [comment]
Sorry that I procrastinated so long on that issue! ;-)
Now that should work.
