### ISSUE TITLE
SPStage +mainStage method

### ISSUE THREAD

**Issue by kylehowells** [PrimaryFeather/Sparrow-Framework#1021]
Adding an [SPStage mainStage]; method would be very useful for a various situations.

**SPStage.h**

``` objc
+ (SPStage*)mainStage;
```

**SPStage.m**

``` objc
+ (SPStage*)mainStage{
    if (stages && [stages count] > 0)
        return  (SPStage*)[stages objectAtIndex:0];
    return nil;
}
```

**Comment by PrimaryFeather** [comment]
Yes, this will be part of Sparrow 1.2 -- thanks for creating the issue, Freerunnering!
