### ISSUE TITLE
Access stage from SPDisplayObject init method

### ISSUE THREAD

**Issue by kylehowells** [PrimaryFeather/Sparrow-Framework#1022]
Dependant on issue #1021.

Allows access to the stage even when the object doesn't have a parent or isn't connected to the stage.

**SPDisplayObject.m**

``` objc
- (SPStage*)stage
{
    SPDisplayObject *root = self.root;
    if ([root isKindOfClass:[SPStage class]]) return (SPStage*) root;
    else return [SPStage mainStage];  /// This line is different.
}
```

**Comment by PrimaryFeather** [comment]
I also thought about this, and I already had this in the source code; then, however, I changed my mind. Some Flash developers use the "stage" property like this:

```
if (self.stage)
  // 'self' is connected to the stage
else
  // 'self' is not connected to the stage
```

And this logic would fail with this change. Thus, I think it's better to leave it as is, and just recommend to developers to use "[SPStage mainStage]" when they want to access the stage in an init-method.
