### ISSUE TITLE
SPView +mainView method

### ISSUE THREAD

**Issue by Shilo** [PrimaryFeather/Sparrow-Framework#1023]

**Comment by brianensorapps** [comment]
Shouldn't this be closed now?

**Comment by PrimaryFeather** [comment]
No, this method does not exist yet -- what I added in Sparrow 1.2 was "[SPStage mainStage]". I am currently rethinking the setup of SPView and SPStage, so I postponed implementing this for now.

**Comment by brianensorapps** [comment]
Oops, sorry. I mixed them up. BTW, I think a revamped upper display tree for 1.3 would be awesome!

**Comment by PrimaryFeather** [comment]
In Sparrow 2.0, you can access the current view controller with "Sparrow.currentController" or the view with "Sparrow.currentController.view".
