### ISSUE TITLE
Orientation support for SPStage or Game

### ISSUE THREAD

**Issue by Shilo** [PrimaryFeather/Sparrow-Framework#1024]
Not sure what would be the best way to go about this, but it would be nice to have orientation support built into Sparrow. Game could subclass an SPSprite, but then adding display objects to SPStage would become obsolete.

**Comment by PrimaryFeather** [comment]
I agree, that would be extremely useful!

**Comment by PrimaryFeather** [comment]
Just a short update: in Sparrow 2.0, this will be added to the core. In Sparrow 1.3, it will (already is) part of the AppScaffold.

**Comment by PrimaryFeather** [comment]
As promised, Sparrow 2.0 handles this automatically. (With the new "SPViewController" class.)
