### ISSUE TITLE
Proper SP_EVENT_TYPE_REMOVED_FROM_STAGE

### ISSUE THREAD

**Issue by Shilo** [PrimaryFeather/Sparrow-Framework#1027]
Could you rename it to SP_EVENT_TYPE_WILL_REMOVE_FROM_STAGE, or add a second event that gets dispatched after it is completely removed from stage? I understand this will not be needed in 99% of cases, but it could prove useful.

If you choose to toss this issue, I am fine with that too. :)
See also: http://forum.sparrow-framework.org/topic/can-you-dispatch-the-remove-events-after

**Comment by PrimaryFeather** [comment]
I understand what you mean, but I'd rather leave it the way it is. Changing the name now would break existing code, and adding a second event would be very problematic, as this code is extremely delicate performance-wise: for every object you add to the stage, this event is created and bubbles up the whole display tree. Having a third of those events would slow this down, without providing much additional value. I hope you agree with that :-)

**Comment by Shilo** [comment]
Yes, I agree.
