### ISSUE TITLE
Add more vector math methods to SPPoint

### ISSUE THREAD

**Issue by PrimaryFeather** [PrimaryFeather/Sparrow-Framework#1042]
As described [here](http://forum.sparrow-framework.org/topic/sppoint-perpendicular).

**Comment by pnutus** [comment]
Don't forget `typedef SPPoint SPVector` for subtracted confusion.

**Comment by PrimaryFeather** [comment]
The latest version adds more utility methods to SPPoint, SPMatrix and SPRectangle. 

I left out the typedef, though: I think people who want that should add that typedef themselves, so that they are aware that it's actually the same class. I fear that newbies (who don't know C) would be confused to have 2 names for the same thing.
