### ISSUE TITLE
AppScaffold Project

### ISSUE THREAD

**Issue by burtlo** [PrimaryFeather/Sparrow-Framework#1059]
AppScaffold Project is unable to build and generates the following error:

```
Argument list too long: recursive header expansion failed at /Applications/Adobe InDesign CS5.5/Adobe InDesign CS5.5.app/Contents/MacOS/Required/Application UI.InDesignPlugin
```

Xcode 4.2.1
Mac OS 10.7.3

**Comment by burtlo** [comment]
My apologies. I failed to read through the building instructions which would set up SPARROW_SRC

**Comment by PrimaryFeather** [comment]
No problem -- that's very easy to miss! I'm glad you found the solution.
