### ISSUE TITLE
SPTextField does not like two line feed with Bitmap Font

### ISSUE THREAD

**Issue by umxprime** [PrimaryFeather/Sparrow-Framework#1063]
Just try this :

``` objective-c
SPTextField *textTest = [SPTextField textFieldWithWidth:500 height:100 text:@"OK\n\n" fontName:kMainFont fontSize:25 color:SP_WHITE];
[self addChild:textTest];
```

then self won't show up on stage...

currently using commit 84759ac9d7edd176e43f52abe300037c3efef980

**Comment by PrimaryFeather** [comment]
Thanks for making me aware of that! I'll fix that ASAP!

**Comment by umxprime** [comment]
It took time to discover why my scene wasn't showing up on simulator (crash on device) due to one of our localization and transition from ttf font to bitmap font ;)

**Comment by PrimaryFeather** [comment]
I fixed that! Thanks again for the report! =)
