### ISSUE TITLE
Testing on Mac

### ISSUE THREAD

**Issue by Kamek** [PrimaryFeather/Sparrow-Framework#1074]
I'd love to be able to test or possibly deploy to mac, any chance of that?

**Comment by PrimaryFeather** [comment]
Hi Kamek!

This is definitely planned! After the Sparrow 2.0 release (which is already worked on), we want to add support for deployment on the Mac. Unfortunately, I can't give you a time schedule for that, though!

Best regards,
Daniel

**Comment by Kamek** [comment]
Awesome, you guys keep up the good work!

**Comment by PrimaryFeather** [comment]
This is actually a duplicate of #1048, so I close this.
A short update: Sparrow 2.0 is almost finished, so I'll soon start to tackle that one. Finally!

**Comment by yderidde** [comment]
Any plan to port it to OSX ? or this was cancelled ?
