### ISSUE TITLE
Resizing a SPQuad width won't work as expected

### ISSUE THREAD

**Issue by raspu** [PrimaryFeather/Sparrow-Framework#1081]
Some how the new value given to the width is reduced.

Ex:

```
currentQuad.width = [self distanceBetweenPoints:cQp and:tp];
NSLog(@"%f - %f",currentQuad.width,[self distanceBetweenPoints:cQp and:tp]);
```

At the log I'm getting:

```
 19.204235 - 170.735748
```

The weird thing is that setting a smaller height value initially, reduces the gap between this two numbers. Could be this be related to scaling?

**Comment by raspu** [comment]
Actually, it seems to be a problem when rotating the SPQuad.

**Comment by PrimaryFeather** [comment]
First of all: SORRY for the late reply!! I totally overlooked this issue. _embarrassing_

I couldn't believe my eyes at first, but you're right! This is really broken. In 3 years of Sparrow and 1.5 years of Starling (which has the same defect), either no one noticed, or no one (except you) took the time to tell me.

I'll look into it!

**Comment by PrimaryFeather** [comment]
Ah, actually I just saw I already looked at this some time ago:
http://forum.sparrow-framework.org/topic/rotation-problem#post-12302

In a nutshell, to correctly solve this, I'd actually have to change the skewing values as well. I'm not yet sure if that's worth it ... hm. I'll have to think about this a little more.

**Comment by raspu** [comment]
No problem, anyway, for anyone looking for the workaround, you should:

Save the rotation, set the rotation to 0, change the size and change the rotation back (Solution by FabianKelschotz).

I haven't tested it, as I'm no longer using Sparrow.

**Comment by PrimaryFeather** [comment]
Yes, that should work!
I'm sorry to hear you're no long using Sparrow -- I hope I didn't shoo you away with my silence in this thread! ;-)

In any case, good luck with your projects! =)

Cheers,
Daniel

**Comment by raspu** [comment]
Don't worry Daniel, I'm no longer trying to develop games, that's the reason why I stop using sparrow.
