### ISSUE TITLE
port sparrow to android

### ISSUE THREAD

**Issue by HiWill** [PrimaryFeather/Sparrow-Framework#1086]
is there any plan to port sparrow to android, like cocos2d-X

**Comment by PrimaryFeather** [comment]
Not at the moment -- it's just too much work for a small team like us to do that. Although I'd love to see it -- it's just not realistic at the moment, sorry!

However, you can use the [Starling Framework](http://www.starling-framework.org) instead: it's cross-platform and works on both Android and iOS, as well as OS X and Windows.
